# -*- coding: utf-8 -*-
"""Frases del bloque de datos de gen_category_content.py, en los 8 idiomas.

Clave -> {idioma: plantilla}. Los huecos {x} los rellena el generador con
datos de la pagina; los mismos huecos van en data-i18n-vars para que
i18n.js traduzca en el navegador. gen_category_content.py copia estas
claves (prefijo "kfd_") a i18n.js (ingles) y lang/<idioma>.js.

Reglas de redaccion: solo datos, sin adjetivos de valor; listas siempre con
dos puntos (asi "y"/"and" no queda a medias en otros idiomas).
{date} = fecha en ingles ("7 October 2026"); {dnum} = "07/10/2026" para el
resto de idiomas.
"""

T = {
    # ── Titulo de la seccion ────────────────────────────────────────────
    "kfd_h_a": {"en": "{team} shirts on Kit Finder: the numbers",
                "es": "Camisetas de {team} en Kit Finder: las cifras",
                "fr": "Maillots {team} sur Kit Finder : les chiffres",
                "de": "{team}-Trikots auf Kit Finder: die Zahlen",
                "it": "Maglie {team} su Kit Finder: i numeri",
                "nl": "{team}-shirts op Kit Finder: de cijfers",
                "pl": "Koszulki {team} w Kit Finder: liczby",
                "pt": "Camisolas do {team} no Kit Finder: os números"},
    "kfd_h_b": {"en": "{team} shirts in stock right now",
                "es": "Camisetas de {team} disponibles ahora",
                "fr": "Maillots {team} disponibles en ce moment",
                "de": "{team}-Trikots, die gerade verfügbar sind",
                "it": "Maglie {team} disponibili ora",
                "nl": "{team}-shirts die nu op voorraad zijn",
                "pl": "Koszulki {team} dostępne teraz",
                "pt": "Camisolas do {team} disponíveis agora"},
    "kfd_h_c": {"en": "What's available for {team} today",
                "es": "Qué hay disponible de {team} hoy",
                "fr": "Ce qui est disponible pour {team} aujourd'hui",
                "de": "Was es heute von {team} gibt",
                "it": "Cosa c'è oggi per {team}",
                "nl": "Wat er vandaag van {team} beschikbaar is",
                "pl": "Co jest dziś dostępne dla {team}",
                "pt": "O que há hoje do {team}"},
    "kfd_h_d": {"en": "{team} shirts by the numbers",
                "es": "Las camisetas de {team} en números",
                "fr": "Les maillots {team} en chiffres",
                "de": "{team}-Trikots in Zahlen",
                "it": "Le maglie {team} in numeri",
                "nl": "{team}-shirts in cijfers",
                "pl": "Koszulki {team} w liczbach",
                "pt": "As camisolas do {team} em números"},

    # ── Resumen ─────────────────────────────────────────────────────────
    "kfd_ov_a": {"en": "Kit Finder currently lists {n} {team} shirts from {s} stores. Prices run from {min} to {max}, and the average is {avg}.",
                 "es": "Kit Finder tiene ahora {n} camisetas de {team} de {s} tiendas. Los precios van de {min} a {max} y la media es {avg}.",
                 "fr": "Kit Finder répertorie actuellement {n} maillots {team} provenant de {s} boutiques. Les prix vont de {min} à {max}, pour une moyenne de {avg}.",
                 "de": "Kit Finder listet derzeit {n} {team}-Trikots aus {s} Shops. Die Preise reichen von {min} bis {max}, der Durchschnitt liegt bei {avg}.",
                 "it": "Kit Finder elenca al momento {n} maglie {team} di {s} negozi. I prezzi vanno da {min} a {max} e la media è {avg}.",
                 "nl": "Kit Finder toont nu {n} {team}-shirts van {s} winkels. De prijzen lopen van {min} tot {max}; het gemiddelde is {avg}.",
                 "pl": "Kit Finder ma obecnie {n} koszulek {team} z {s} sklepów. Ceny wynoszą od {min} do {max}, a średnia to {avg}.",
                 "pt": "O Kit Finder lista neste momento {n} camisolas do {team} de {s} lojas. Os preços vão de {min} a {max} e a média é {avg}."},
    "kfd_ov_b": {"en": "Right now there are {n} {team} shirts on Kit Finder, spread across {s} stores. The cheapest costs {min} and the most expensive {max}; half of them cost less than {median}.",
                 "es": "Ahora mismo hay {n} camisetas de {team} en Kit Finder, repartidas entre {s} tiendas. La más barata cuesta {min} y la más cara {max}; la mitad cuesta menos de {median}.",
                 "fr": "Il y a en ce moment {n} maillots {team} sur Kit Finder, répartis entre {s} boutiques. Le moins cher coûte {min} et le plus cher {max} ; la moitié coûte moins de {median}.",
                 "de": "Aktuell gibt es {n} {team}-Trikots auf Kit Finder, verteilt auf {s} Shops. Das günstigste kostet {min}, das teuerste {max}; die Hälfte kostet weniger als {median}.",
                 "it": "In questo momento ci sono {n} maglie {team} su Kit Finder, distribuite tra {s} negozi. La più economica costa {min} e la più cara {max}; metà costano meno di {median}.",
                 "nl": "Op dit moment staan er {n} {team}-shirts op Kit Finder, verdeeld over {s} winkels. Het goedkoopste kost {min} en het duurste {max}; de helft kost minder dan {median}.",
                 "pl": "W tej chwili w Kit Finder jest {n} koszulek {team} z {s} sklepów. Najtańsza kosztuje {min}, najdroższa {max}; połowa kosztuje mniej niż {median}.",
                 "pt": "Neste momento há {n} camisolas do {team} no Kit Finder, distribuídas por {s} lojas. A mais barata custa {min} e a mais cara {max}; metade custa menos de {median}."},
    "kfd_ov_c": {"en": "{s} stores currently stock {team} shirts, {n} listings in total. A typical one costs about {median} (the middle price), while the average across all of them is {avg}.",
                 "es": "{s} tiendas tienen ahora camisetas de {team}, {n} anuncios en total. Una típica cuesta unos {median} (el precio mediano) y la media de todas es {avg}.",
                 "fr": "{s} boutiques proposent actuellement des maillots {team}, soit {n} annonces au total. Un maillot typique coûte environ {median} (le prix médian) et la moyenne de l'ensemble est de {avg}.",
                 "de": "{s} Shops führen derzeit {team}-Trikots, insgesamt {n} Angebote. Ein typisches kostet etwa {median} (der mittlere Preis), der Durchschnitt aller liegt bei {avg}.",
                 "it": "{s} negozi hanno ora maglie {team}, {n} annunci in tutto. Una maglia tipica costa circa {median} (il prezzo mediano), mentre la media di tutte è {avg}.",
                 "nl": "{s} winkels hebben nu {team}-shirts, samen {n} advertenties. Een typisch shirt kost ongeveer {median} (de middelste prijs); het gemiddelde van alle shirts is {avg}.",
                 "pl": "{s} sklepów ma obecnie koszulki {team}, łącznie {n} ofert. Typowa kosztuje około {median} (cena środkowa), a średnia wszystkich to {avg}.",
                 "pt": "{s} lojas têm neste momento camisolas do {team}, {n} anúncios no total. Uma típica custa cerca de {median} (o preço mediano) e a média de todas é {avg}."},
    "kfd_ov_d": {"en": "Our search index holds {n} {team} shirts today, gathered from {s} stores. Asking prices start at {min} and go up to {max}.",
                 "es": "Nuestro índice de búsqueda tiene hoy {n} camisetas de {team}, recogidas de {s} tiendas. Los precios empiezan en {min} y llegan a {max}.",
                 "fr": "Notre index de recherche contient aujourd'hui {n} maillots {team}, issus de {s} boutiques. Les prix démarrent à {min} et montent jusqu'à {max}.",
                 "de": "Unser Suchindex enthält heute {n} {team}-Trikots aus {s} Shops. Die Preise beginnen bei {min} und reichen bis {max}.",
                 "it": "Il nostro indice di ricerca contiene oggi {n} maglie {team}, raccolte da {s} negozi. I prezzi partono da {min} e arrivano a {max}.",
                 "nl": "Onze zoekindex bevat vandaag {n} {team}-shirts, verzameld uit {s} winkels. De vraagprijzen beginnen bij {min} en lopen op tot {max}.",
                 "pl": "Nasz indeks wyszukiwania zawiera dziś {n} koszulek {team} z {s} sklepów. Ceny zaczynają się od {min} i sięgają {max}.",
                 "pt": "O nosso índice de pesquisa tem hoje {n} camisolas do {team}, recolhidas de {s} lojas. Os preços começam em {min} e chegam a {max}."},
    "kfd_ov_1s": {"en": "Kit Finder currently lists {n} {team} shirts, all from one store: {store}. Prices run from {min} to {max}.",
                  "es": "Kit Finder tiene ahora {n} camisetas de {team}, todas de una sola tienda: {store}. Los precios van de {min} a {max}.",
                  "fr": "Kit Finder répertorie actuellement {n} maillots {team}, tous issus d'une seule boutique : {store}. Les prix vont de {min} à {max}.",
                  "de": "Kit Finder listet derzeit {n} {team}-Trikots, alle aus einem Shop: {store}. Die Preise reichen von {min} bis {max}.",
                  "it": "Kit Finder elenca al momento {n} maglie {team}, tutte da un solo negozio: {store}. I prezzi vanno da {min} a {max}.",
                  "nl": "Kit Finder toont nu {n} {team}-shirts, allemaal van één winkel: {store}. De prijzen lopen van {min} tot {max}.",
                  "pl": "Kit Finder ma obecnie {n} koszulek {team}, wszystkie z jednego sklepu: {store}. Ceny wynoszą od {min} do {max}.",
                  "pt": "O Kit Finder lista neste momento {n} camisolas do {team}, todas de uma só loja: {store}. Os preços vão de {min} a {max}."},
    "kfd_ov_one": {"en": "Kit Finder currently has a single {team} shirt listed, priced at {min}.",
                   "es": "Kit Finder tiene ahora una sola camiseta de {team}, a {min}.",
                   "fr": "Kit Finder ne répertorie actuellement qu'un seul maillot {team}, au prix de {min}.",
                   "de": "Kit Finder listet derzeit ein einziges {team}-Trikot, zum Preis von {min}.",
                   "it": "Kit Finder elenca al momento una sola maglia {team}, a {min}.",
                   "nl": "Kit Finder toont nu één {team}-shirt, voor {min}.",
                   "pl": "Kit Finder ma obecnie tylko jedną koszulkę {team}, w cenie {min}.",
                   "pt": "O Kit Finder tem neste momento uma só camisola do {team}, a {min}."},
    "kfd_px_a": {"en": "{p50} are under €50 and {p200} are over €200.",
                 "es": "El {p50} cuesta menos de 50 € y el {p200} más de 200 €.",
                 "fr": "{p50} coûtent moins de 50 € et {p200} plus de 200 €.",
                 "de": "{p50} kosten unter 50 € und {p200} über 200 €.",
                 "it": "Il {p50} costa meno di 50 € e il {p200} più di 200 €.",
                 "nl": "{p50} kost minder dan € 50 en {p200} meer dan € 200.",
                 "pl": "{p50} kosztuje poniżej 50 €, a {p200} powyżej 200 €.",
                 "pt": "{p50} custam menos de 50 € e {p200} mais de 200 €."},
    "kfd_px_b": {"en": "{c50} of them cost less than €50; {c200} are priced above €200.",
                 "es": "{c50} cuestan menos de 50 €; {c200} pasan de 200 €.",
                 "fr": "{c50} d'entre eux coûtent moins de 50 € ; {c200} dépassent 200 €.",
                 "de": "{c50} davon kosten weniger als 50 €; {c200} liegen über 200 €.",
                 "it": "{c50} costano meno di 50 €; {c200} superano i 200 €.",
                 "nl": "{c50} daarvan kosten minder dan € 50; {c200} zijn duurder dan € 200.",
                 "pl": "{c50} z nich kosztuje mniej niż 50 €; {c200} ma cenę powyżej 200 €.",
                 "pt": "{c50} custam menos de 50 €; {c200} custam mais de 200 €."},
    "kfd_px_c": {"en": "About {p50} sit below €50.",
                 "es": "Cerca del {p50} está por debajo de 50 €.",
                 "fr": "Environ {p50} sont sous les 50 €.",
                 "de": "Etwa {p50} liegen unter 50 €.",
                 "it": "Circa il {p50} è sotto i 50 €.",
                 "nl": "Ongeveer {p50} zit onder de € 50.",
                 "pl": "Około {p50} kosztuje mniej niż 50 €.",
                 "pt": "Cerca de {p50} estão abaixo dos 50 €."},

    # ── Temporadas y decadas ───────────────────────────────────────────
    "kfd_era_a": {"en": "Listed seasons range from {oldest} to {newest}, {k} different seasons in all.",
                  "es": "Las temporadas van de {oldest} a {newest}: {k} temporadas distintas en total.",
                  "fr": "Les saisons vont de {oldest} à {newest}, soit {k} saisons différentes.",
                  "de": "Die Saisons reichen von {oldest} bis {newest}, insgesamt {k} verschiedene.",
                  "it": "Le stagioni vanno dal {oldest} al {newest}: {k} stagioni diverse in tutto.",
                  "nl": "De seizoenen lopen van {oldest} tot {newest}, in totaal {k} verschillende seizoenen.",
                  "pl": "Sezony obejmują lata od {oldest} do {newest}, łącznie {k} różnych sezonów.",
                  "pt": "As épocas vão de {oldest} a {newest}, {k} épocas diferentes no total."},
    "kfd_era_b": {"en": "The oldest season we can find for {team} is {oldest}; the most recent is {newest}.",
                  "es": "La temporada más antigua que tenemos de {team} es {oldest}; la más reciente, {newest}.",
                  "fr": "La saison la plus ancienne que nous trouvons pour {team} est {oldest} ; la plus récente, {newest}.",
                  "de": "Die älteste Saison, die wir für {team} finden, ist {oldest}; die neueste {newest}.",
                  "it": "La stagione più vecchia che troviamo per {team} è {oldest}; la più recente {newest}.",
                  "nl": "Het oudste seizoen dat we voor {team} vinden is {oldest}; het nieuwste {newest}.",
                  "pl": "Najstarszy sezon {team}, jaki znajdujemy, to {oldest}; najnowszy to {newest}.",
                  "pt": "A época mais antiga que encontramos do {team} é {oldest}; a mais recente, {newest}."},
    "kfd_era_c": {"en": "Across {k} seasons, the earliest {team} shirt in stock is from {oldest} and the latest from {newest}.",
                  "es": "Entre {k} temporadas, la camiseta de {team} más antigua es de {oldest} y la más nueva de {newest}.",
                  "fr": "Sur {k} saisons, le plus ancien maillot {team} en stock date de {oldest} et le plus récent de {newest}.",
                  "de": "Über {k} Saisons hinweg stammt das älteste {team}-Trikot aus {oldest}, das neueste aus {newest}.",
                  "it": "Su {k} stagioni, la maglia {team} più vecchia è del {oldest} e la più recente del {newest}.",
                  "nl": "Verspreid over {k} seizoenen is het oudste {team}-shirt van {oldest} en het nieuwste van {newest}.",
                  "pl": "W {k} sezonach najstarsza koszulka {team} pochodzi z {oldest}, a najnowsza z {newest}.",
                  "pt": "Em {k} épocas, a camisola do {team} mais antiga é de {oldest} e a mais recente de {newest}."},
    "kfd_dec_a": {"en": "The {dec}s are the best-stocked decade, with {c} dated listings.",
                  "es": "La década con más camisetas es la de {dec}, con {c} anuncios con fecha.",
                  "fr": "Les années {dec} sont la décennie la mieux fournie, avec {c} annonces datées.",
                  "de": "Die {dec}er-Jahre sind das am besten bestückte Jahrzehnt, mit {c} datierten Angeboten.",
                  "it": "Gli anni {dec} sono il decennio più fornito, con {c} annunci datati.",
                  "nl": "De jaren {dec} zijn het best gevulde decennium, met {c} gedateerde advertenties.",
                  "pl": "Najwięcej ofert pochodzi z lat {dec}: {c} z podanym sezonem.",
                  "pt": "Os anos {dec} são a década com mais oferta, com {c} anúncios datados."},
    "kfd_dec_b": {"en": "Most dated listings come from the {dec}s ({p}).",
                  "es": "La mayoría de anuncios con fecha son de la década de {dec} ({p}).",
                  "fr": "La plupart des annonces datées viennent des années {dec} ({p}).",
                  "de": "Die meisten datierten Angebote stammen aus den {dec}er-Jahren ({p}).",
                  "it": "La maggior parte degli annunci datati viene dagli anni {dec} ({p}).",
                  "nl": "De meeste gedateerde advertenties komen uit de jaren {dec} ({p}).",
                  "pl": "Większość ofert z podanym sezonem pochodzi z lat {dec} ({p}).",
                  "pt": "A maioria dos anúncios datados é dos anos {dec} ({p})."},
    "kfd_dec_c": {"en": "By decade, the {dec}s lead with {c} shirts, ahead of the {dec2}s with {c2}.",
                  "es": "Por décadas, la de {dec} va primera con {c} camisetas, por delante de la de {dec2} con {c2}.",
                  "fr": "Par décennie, les années {dec} arrivent en tête avec {c} maillots, devant les années {dec2} avec {c2}.",
                  "de": "Nach Jahrzehnten führen die {dec}er mit {c} Trikots, vor den {dec2}ern mit {c2}.",
                  "it": "Per decennio, gli anni {dec} sono in testa con {c} maglie, davanti agli anni {dec2} con {c2}.",
                  "nl": "Per decennium staan de jaren {dec} bovenaan met {c} shirts, voor de jaren {dec2} met {c2}.",
                  "pl": "Według dekad prowadzą lata {dec} z {c} koszulkami, przed latami {dec2} z {c2}.",
                  "pt": "Por década, os anos {dec} lideram com {c} camisolas, à frente dos anos {dec2} com {c2}."},
    "kfd_top_a": {"en": "The single most-listed season is {season} ({c} shirts).",
                  "es": "La temporada con más anuncios es {season} ({c} camisetas).",
                  "fr": "La saison la plus représentée est {season} ({c} maillots).",
                  "de": "Die Saison mit den meisten Angeboten ist {season} ({c} Trikots).",
                  "it": "La stagione con più annunci è il {season} ({c} maglie).",
                  "nl": "Het seizoen met de meeste advertenties is {season} ({c} shirts).",
                  "pl": "Sezon z największą liczbą ofert to {season} ({c} koszulek).",
                  "pt": "A época com mais anúncios é {season} ({c} camisolas)."},
    "kfd_top_b": {"en": "{season} is the season with the most shirts for sale: {c}.",
                  "es": "{season} es la temporada con más camisetas a la venta: {c}.",
                  "fr": "{season} est la saison qui compte le plus de maillots en vente : {c}.",
                  "de": "{season} ist die Saison mit den meisten Trikots im Angebot: {c}.",
                  "it": "Il {season} è la stagione con più maglie in vendita: {c}.",
                  "nl": "{season} is het seizoen met de meeste shirts te koop: {c}.",
                  "pl": "{season} to sezon z największą liczbą koszulek na sprzedaż: {c}.",
                  "pt": "{season} é a época com mais camisolas à venda: {c}."},
    "kfd_nod_a": {"en": "{p} of listings don't state a season.",
                  "es": "El {p} de los anuncios no indica temporada.",
                  "fr": "{p} des annonces n'indiquent pas de saison.",
                  "de": "{p} der Angebote nennen keine Saison.",
                  "it": "Il {p} degli annunci non indica la stagione.",
                  "nl": "{p} van de advertenties vermeldt geen seizoen.",
                  "pl": "{p} ofert nie podaje sezonu.",
                  "pt": "{p} dos anúncios não indicam a época."},
    "kfd_nod_b": {"en": "Stores give no season for {c} of the listings.",
                  "es": "Las tiendas no indican temporada en {c} anuncios.",
                  "fr": "Les boutiques n'indiquent pas de saison pour {c} annonces.",
                  "de": "Bei {c} Angeboten geben die Shops keine Saison an.",
                  "it": "I negozi non indicano la stagione per {c} annunci.",
                  "nl": "Bij {c} advertenties geven de winkels geen seizoen op.",
                  "pl": "Sklepy nie podają sezonu w {c} ofertach.",
                  "pt": "As lojas não indicam a época em {c} anúncios."},

    # ── Tipo de equipacion y manga ─────────────────────────────────────
    "kfd_kit_a": {"en": "Of the {c} listings that say which kit they are, {home} are home, {away} away and {third} third.",
                  "es": "De los {c} anuncios que indican la equipación, el {home} es de local, el {away} de visitante y el {third} tercera.",
                  "fr": "Parmi les {c} annonces qui précisent le maillot, {home} sont domicile, {away} extérieur et {third} third.",
                  "de": "Von den {c} Angeboten mit Angabe des Trikots sind {home} Heim-, {away} Auswärts- und {third} Ausweichtrikots.",
                  "it": "Dei {c} annunci che indicano la divisa, il {home} è home, il {away} away e il {third} third.",
                  "nl": "Van de {c} advertenties die het tenue vermelden, is {home} thuis, {away} uit en {third} derde tenue.",
                  "pl": "Spośród {c} ofert z podanym rodzajem stroju {home} to domowe, {away} wyjazdowe, a {third} trzecie.",
                  "pt": "Dos {c} anúncios que indicam o equipamento, {home} são principais, {away} alternativos e {third} terceiros."},
    "kfd_kit_b": {"en": "Where the kit type is stated ({c} listings), the split is {home} home, {away} away and {third} third.",
                  "es": "Cuando se indica la equipación ({c} anuncios), el reparto es {home} local, {away} visitante y {third} tercera.",
                  "fr": "Lorsque le type de maillot est indiqué ({c} annonces), la répartition est de {home} domicile, {away} extérieur et {third} third.",
                  "de": "Wo die Trikotart angegeben ist ({c} Angebote), verteilt es sich auf {home} Heim, {away} Auswärts und {third} Ausweich.",
                  "it": "Dove è indicato il tipo di divisa ({c} annunci), la ripartizione è {home} home, {away} away e {third} third.",
                  "nl": "Waar het type tenue vermeld staat ({c} advertenties), is de verdeling {home} thuis, {away} uit en {third} derde.",
                  "pl": "Tam, gdzie podano rodzaj stroju ({c} ofert), podział wynosi: {home} domowe, {away} wyjazdowe, {third} trzecie.",
                  "pt": "Quando o tipo de equipamento é indicado ({c} anúncios), a divisão é {home} principal, {away} alternativo e {third} terceiro."},
    "kfd_kit_c": {"en": "Kit types, among listings that specify one: {home} home, {away} away, {third} third.",
                  "es": "Tipos de equipación, entre los anuncios que la indican: {home} local, {away} visitante, {third} tercera.",
                  "fr": "Types de maillot, parmi les annonces qui le précisent : {home} domicile, {away} extérieur, {third} third.",
                  "de": "Trikotarten, soweit angegeben: {home} Heim, {away} Auswärts, {third} Ausweich.",
                  "it": "Tipi di divisa, tra gli annunci che lo indicano: {home} home, {away} away, {third} third.",
                  "nl": "Soorten tenue, bij advertenties die het vermelden: {home} thuis, {away} uit, {third} derde.",
                  "pl": "Rodzaje strojów w ofertach, które je podają: {home} domowe, {away} wyjazdowe, {third} trzecie.",
                  "pt": "Tipos de equipamento, nos anúncios que o indicam: {home} principal, {away} alternativo, {third} terceiro."},
    "kfd_gk": {"en": "Goalkeeper shirts make up {gk} of them.",
               "es": "Las de portero son el {gk}.",
               "fr": "Les maillots de gardien en représentent {gk}.",
               "de": "Torwarttrikots machen {gk} davon aus.",
               "it": "Le maglie da portiere sono il {gk}.",
               "nl": "Keepersshirts zijn goed voor {gk}.",
               "pl": "Koszulki bramkarskie stanowią {gk}.",
               "pt": "As camisolas de guarda-redes são {gk}."},
    "kfd_ls_a": {"en": "{c} are marked as long-sleeve.",
                 "es": "{c} están marcadas como de manga larga.",
                 "fr": "{c} sont indiqués à manches longues.",
                 "de": "{c} sind als Langarm gekennzeichnet.",
                 "it": "{c} sono indicate a maniche lunghe.",
                 "nl": "{c} staan aangemerkt als lange mouw.",
                 "pl": "{c} oznaczono jako z długim rękawem.",
                 "pt": "{c} estão marcadas como de manga comprida."},
    "kfd_ls_b": {"en": "Long-sleeve versions: {c} listings.",
                 "es": "Versiones de manga larga: {c} anuncios.",
                 "fr": "Versions à manches longues : {c} annonces.",
                 "de": "Langarm-Versionen: {c} Angebote.",
                 "it": "Versioni a maniche lunghe: {c} annunci.",
                 "nl": "Versies met lange mouw: {c} advertenties.",
                 "pl": "Wersje z długim rękawem: {c} ofert.",
                 "pt": "Versões de manga comprida: {c} anúncios."},
    "kfd_ls_c": {"en": "Stores flag {c} of them as long-sleeve shirts.",
                 "es": "Las tiendas marcan {c} como de manga larga.",
                 "fr": "Les boutiques en signalent {c} à manches longues.",
                 "de": "Die Shops kennzeichnen {c} davon als Langarmtrikots.",
                 "it": "I negozi ne segnalano {c} a maniche lunghe.",
                 "nl": "Winkels markeren er {c} als shirt met lange mouw.",
                 "pl": "Sklepy oznaczają {c} z nich jako koszulki z długim rękawem.",
                 "pt": "As lojas marcam {c} como de manga comprida."},

    # ── Marcas y tiendas ───────────────────────────────────────────────
    "kfd_br_a": {"en": "Most common manufacturers among branded listings: {list}.",
                 "es": "Fabricantes más habituales entre los anuncios con marca: {list}.",
                 "fr": "Équipementiers les plus fréquents parmi les annonces avec marque : {list}.",
                 "de": "Häufigste Hersteller unter den Angeboten mit Marke: {list}.",
                 "it": "Produttori più frequenti tra gli annunci con marca: {list}.",
                 "nl": "Meest voorkomende merken bij advertenties met merk: {list}.",
                 "pl": "Najczęstsi producenci wśród ofert z podaną marką: {list}.",
                 "pt": "Marcas mais frequentes nos anúncios com marca: {list}."},
    "kfd_br_b": {"en": "{brand} is the most listed maker ({p} of branded listings).",
                 "es": "{brand} es la marca con más anuncios ({p} de los que indican marca).",
                 "fr": "{brand} est l'équipementier le plus présent ({p} des annonces avec marque).",
                 "de": "{brand} ist der am häufigsten gelistete Hersteller ({p} der Angebote mit Marke).",
                 "it": "{brand} è il marchio più presente ({p} degli annunci con marca).",
                 "nl": "{brand} is het vaakst vermelde merk ({p} van de advertenties met merk).",
                 "pl": "{brand} to najczęściej wystawiana marka ({p} ofert z podaną marką).",
                 "pt": "{brand} é a marca com mais anúncios ({p} dos anúncios com marca)."},
    "kfd_br_c": {"en": "Brands seen most often: {list}.",
                 "es": "Marcas más vistas: {list}.",
                 "fr": "Marques les plus vues : {list}.",
                 "de": "Am häufigsten gesehene Marken: {list}.",
                 "it": "Marchi più visti: {list}.",
                 "nl": "Vaakst geziene merken: {list}.",
                 "pl": "Najczęściej spotykane marki: {list}.",
                 "pt": "Marcas mais vistas: {list}."},
    "kfd_st_a": {"en": "The stores with the most stock: {list}.",
                 "es": "Las tiendas con más stock: {list}.",
                 "fr": "Les boutiques les mieux fournies : {list}.",
                 "de": "Die Shops mit dem größten Bestand: {list}.",
                 "it": "I negozi con più disponibilità: {list}.",
                 "nl": "De winkels met de meeste voorraad: {list}.",
                 "pl": "Sklepy z największą liczbą ofert: {list}.",
                 "pt": "As lojas com mais stock: {list}."},
    "kfd_st_b": {"en": "{store} has the largest selection, with {c} shirts.",
                 "es": "{store} tiene la mayor selección, con {c} camisetas.",
                 "fr": "{store} a le plus grand choix, avec {c} maillots.",
                 "de": "{store} hat die größte Auswahl, mit {c} Trikots.",
                 "it": "{store} ha la selezione più ampia, con {c} maglie.",
                 "nl": "{store} heeft het grootste aanbod, met {c} shirts.",
                 "pl": "{store} ma największy wybór: {c} koszulek.",
                 "pt": "{store} tem a maior seleção, com {c} camisolas."},
    "kfd_st_c": {"en": "Biggest sellers on Kit Finder: {list}.",
                 "es": "Vendedores con más anuncios en Kit Finder: {list}.",
                 "fr": "Plus gros vendeurs sur Kit Finder : {list}.",
                 "de": "Größte Anbieter auf Kit Finder: {list}.",
                 "it": "Venditori più grandi su Kit Finder: {list}.",
                 "nl": "Grootste verkopers op Kit Finder: {list}.",
                 "pl": "Najwięksi sprzedawcy w Kit Finder: {list}.",
                 "pt": "Maiores vendedores no Kit Finder: {list}."},

    # ── Mas barata / mas cara ──────────────────────────────────────────
    "kfd_ex_a": {"en": "Cheapest right now: {lo}. Most expensive: {hi}.",
                 "es": "La más barata ahora: {lo}. La más cara: {hi}.",
                 "fr": "Le moins cher en ce moment : {lo}. Le plus cher : {hi}.",
                 "de": "Aktuell am günstigsten: {lo}. Am teuersten: {hi}.",
                 "it": "La più economica ora: {lo}. La più cara: {hi}.",
                 "nl": "Nu het goedkoopst: {lo}. Het duurst: {hi}.",
                 "pl": "Najtańsza teraz: {lo}. Najdroższa: {hi}.",
                 "pt": "A mais barata agora: {lo}. A mais cara: {hi}."},
    "kfd_ex_b": {"en": "At the bottom of the price range is {lo}; at the top, {hi}.",
                 "es": "En lo más bajo de precio está {lo}; en lo más alto, {hi}.",
                 "fr": "En bas de la fourchette de prix : {lo} ; en haut : {hi}.",
                 "de": "Am unteren Ende der Preisspanne: {lo}; am oberen: {hi}.",
                 "it": "In fondo alla fascia di prezzo c'è {lo}; in cima, {hi}.",
                 "nl": "Onderaan de prijsklasse staat {lo}; bovenaan {hi}.",
                 "pl": "Na dole przedziału cenowego: {lo}; na górze: {hi}.",
                 "pt": "No fundo da gama de preços está {lo}; no topo, {hi}."},
    "kfd_ex_c": {"en": "The lowest-priced listing today is {lo}, and the highest {hi}.",
                 "es": "El anuncio más barato hoy es {lo} y el más caro {hi}.",
                 "fr": "L'annonce la moins chère aujourd'hui est {lo}, la plus chère {hi}.",
                 "de": "Das günstigste Angebot heute ist {lo}, das teuerste {hi}.",
                 "it": "L'annuncio più economico oggi è {lo}, il più caro {hi}.",
                 "nl": "De goedkoopste advertentie vandaag is {lo}, de duurste {hi}.",
                 "pl": "Najtańsza oferta dziś to {lo}, najdroższa {hi}.",
                 "pt": "O anúncio mais barato hoje é {lo} e o mais caro {hi}."},

    # ── Ligas ──────────────────────────────────────────────────────────
    "kfd_lg_a": {"en": "{k} clubs we group under the {team} have shirts listed. The most stocked: {list}.",
                 "es": "{k} clubes que agrupamos en {team} tienen camisetas a la venta. Los que más: {list}.",
                 "fr": "{k} clubs que nous classons en {team} ont des maillots en vente. Les mieux fournis : {list}.",
                 "de": "{k} Klubs, die wir der {team} zuordnen, haben Trikots im Angebot. Am meisten: {list}.",
                 "it": "{k} club che raggruppiamo nella {team} hanno maglie in vendita. I più forniti: {list}.",
                 "nl": "{k} clubs die we onder de {team} rekenen hebben shirts te koop. Het meest: {list}.",
                 "pl": "{k} klubów, które zaliczamy do {team}, ma koszulki w ofercie. Najwięcej: {list}.",
                 "pt": "{k} clubes que agrupamos na {team} têm camisolas à venda. Os com mais oferta: {list}."},
    "kfd_lg_b": {"en": "Shirts from {k} clubs on our {team} list are in stock. Most listings: {list}.",
                 "es": "Hay camisetas de {k} clubes de nuestra lista de {team}. Con más anuncios: {list}.",
                 "fr": "Des maillots de {k} clubs de notre liste {team} sont disponibles. Le plus d'annonces : {list}.",
                 "de": "Trikots von {k} Klubs aus unserer {team}-Liste sind verfügbar. Die meisten Angebote: {list}.",
                 "it": "Ci sono maglie di {k} club della nostra lista {team}. Con più annunci: {list}.",
                 "nl": "Er zijn shirts van {k} clubs uit onze {team}-lijst. De meeste advertenties: {list}.",
                 "pl": "Dostępne są koszulki {k} klubów z naszej listy {team}. Najwięcej ofert: {list}.",
                 "pt": "Há camisolas de {k} clubes da nossa lista da {team}. Com mais anúncios: {list}."},
    "kfd_lg_c": {"en": "Clubs on our {team} list with the biggest selections ({k} clubs have listings): {list}.",
                 "es": "Clubes de nuestra lista de {team} con más selección ({k} clubes tienen anuncios): {list}.",
                 "fr": "Clubs de notre liste {team} avec le plus grand choix ({k} clubs ont des annonces) : {list}.",
                 "de": "Klubs aus unserer {team}-Liste mit der größten Auswahl ({k} Klubs haben Angebote): {list}.",
                 "it": "Club della nostra lista {team} con la scelta più ampia ({k} club hanno annunci): {list}.",
                 "nl": "Clubs uit onze {team}-lijst met het grootste aanbod ({k} clubs hebben advertenties): {list}.",
                 "pl": "Kluby z naszej listy {team} z największym wyborem ({k} klubów ma oferty): {list}.",
                 "pt": "Clubes da nossa lista da {team} com mais escolha ({k} clubes têm anúncios): {list}."},

    # ── Tabla y listas ─────────────────────────────────────────────────
    "kfd_t_n": {"en": "Shirts listed", "es": "Camisetas", "fr": "Maillots répertoriés", "de": "Gelistete Trikots",
                "it": "Maglie elencate", "nl": "Shirts", "pl": "Koszulki w ofercie", "pt": "Camisolas"},
    "kfd_t_s": {"en": "Stores", "es": "Tiendas", "fr": "Boutiques", "de": "Shops", "it": "Negozi",
                "nl": "Winkels", "pl": "Sklepy", "pt": "Lojas"},
    "kfd_t_range": {"en": "Price range", "es": "Rango de precios", "fr": "Fourchette de prix", "de": "Preisspanne",
                    "it": "Fascia di prezzo", "nl": "Prijsklasse", "pl": "Przedział cen", "pt": "Gama de preços"},
    "kfd_t_avg": {"en": "Average price", "es": "Precio medio", "fr": "Prix moyen", "de": "Durchschnittspreis",
                  "it": "Prezzo medio", "nl": "Gemiddelde prijs", "pl": "Średnia cena", "pt": "Preço médio"},
    "kfd_t_med": {"en": "Middle (median) price", "es": "Precio mediano", "fr": "Prix médian", "de": "Mittlerer Preis (Median)",
                  "it": "Prezzo mediano", "nl": "Middelste prijs (mediaan)", "pl": "Cena środkowa (mediana)", "pt": "Preço mediano"},
    "kfd_t_seasons": {"en": "Seasons listed", "es": "Temporadas", "fr": "Saisons", "de": "Saisons", "it": "Stagioni",
                      "nl": "Seizoenen", "pl": "Sezony", "pt": "Épocas"},
    "kfd_t_brand": {"en": "Top brand", "es": "Marca principal", "fr": "Marque principale", "de": "Häufigste Marke",
                    "it": "Marchio principale", "nl": "Meest voorkomend merk", "pl": "Najczęstsza marka", "pt": "Marca principal"},
    "kfd_t_ls": {"en": "Long-sleeve", "es": "Manga larga", "fr": "Manches longues", "de": "Langarm", "it": "Maniche lunghe",
                 "nl": "Lange mouw", "pl": "Długi rękaw", "pt": "Manga comprida"},
    "kfd_l_clubs_a": {"en": "Clubs on our {team} list with the most shirts",
                      "es": "Clubes de nuestra lista de {team} con más camisetas",
                      "fr": "Clubs de notre liste {team} avec le plus de maillots",
                      "de": "Klubs aus unserer {team}-Liste mit den meisten Trikots",
                      "it": "Club della nostra lista {team} con più maglie",
                      "nl": "Clubs uit onze {team}-lijst met de meeste shirts",
                      "pl": "Kluby z naszej listy {team} z największą liczbą koszulek",
                      "pt": "Clubes da nossa lista da {team} com mais camisolas"},
    "kfd_l_clubs_b": {"en": "Most-stocked clubs on our {team} list",
                      "es": "Clubes de nuestra lista de {team} con más stock",
                      "fr": "Clubs les mieux fournis de notre liste {team}",
                      "de": "Am besten bestückte Klubs aus unserer {team}-Liste",
                      "it": "Club più forniti della nostra lista {team}",
                      "nl": "Best gevulde clubs uit onze {team}-lijst",
                      "pl": "Kluby z naszej listy {team} z największą ofertą",
                      "pt": "Clubes da nossa lista da {team} com mais oferta"},
    "kfd_l_seas_a": {"en": "Most-listed seasons", "es": "Temporadas con más anuncios", "fr": "Saisons les plus représentées",
                     "de": "Saisons mit den meisten Angeboten", "it": "Stagioni con più annunci", "nl": "Seizoenen met de meeste advertenties",
                     "pl": "Sezony z największą liczbą ofert", "pt": "Épocas com mais anúncios"},
    "kfd_l_seas_b": {"en": "Seasons with the most shirts", "es": "Temporadas con más camisetas", "fr": "Saisons avec le plus de maillots",
                     "de": "Saisons mit den meisten Trikots", "it": "Stagioni con più maglie", "nl": "Seizoenen met de meeste shirts",
                     "pl": "Sezony z największą liczbą koszulek", "pt": "Épocas com mais camisolas"},
    "kfd_l_seas_c": {"en": "Top seasons by number of listings", "es": "Temporadas principales por número de anuncios",
                     "fr": "Principales saisons par nombre d'annonces", "de": "Top-Saisons nach Anzahl der Angebote",
                     "it": "Stagioni principali per numero di annunci", "nl": "Topseizoenen naar aantal advertenties",
                     "pl": "Najważniejsze sezony według liczby ofert", "pt": "Principais épocas por número de anúncios"},
    "kfd_l_dec_a": {"en": "Listings by decade", "es": "Anuncios por década", "fr": "Annonces par décennie", "de": "Angebote nach Jahrzehnt",
                    "it": "Annunci per decennio", "nl": "Advertenties per decennium", "pl": "Oferty według dekad", "pt": "Anúncios por década"},
    "kfd_l_dec_b": {"en": "Shirts per decade", "es": "Camisetas por década", "fr": "Maillots par décennie", "de": "Trikots pro Jahrzehnt",
                    "it": "Maglie per decennio", "nl": "Shirts per decennium", "pl": "Koszulki według dekad", "pt": "Camisolas por década"},

    # ── FAQ ────────────────────────────────────────────────────────────
    "kfd_faq_a": {"en": "Questions about these shirts", "es": "Preguntas sobre estas camisetas", "fr": "Questions sur ces maillots",
                  "de": "Fragen zu diesen Trikots", "it": "Domande su queste maglie", "nl": "Vragen over deze shirts",
                  "pl": "Pytania o te koszulki", "pt": "Perguntas sobre estas camisolas"},
    "kfd_faq_b": {"en": "FAQ", "es": "Preguntas frecuentes", "fr": "FAQ", "de": "FAQ", "it": "FAQ", "nl": "Veelgestelde vragen",
                  "pl": "FAQ", "pt": "Perguntas frequentes"},
    "kfd_faq_c": {"en": "Quick answers", "es": "Respuestas rápidas", "fr": "Réponses rapides", "de": "Kurze Antworten",
                  "it": "Risposte rapide", "nl": "Snelle antwoorden", "pl": "Szybkie odpowiedzi", "pt": "Respostas rápidas"},
    "kfd_q_n_a": {"en": "How many {team} shirts are on Kit Finder?", "es": "¿Cuántas camisetas de {team} hay en Kit Finder?",
                  "fr": "Combien de maillots {team} y a-t-il sur Kit Finder ?", "de": "Wie viele {team}-Trikots gibt es auf Kit Finder?",
                  "it": "Quante maglie {team} ci sono su Kit Finder?", "nl": "Hoeveel {team}-shirts staan er op Kit Finder?",
                  "pl": "Ile koszulek {team} jest w Kit Finder?", "pt": "Quantas camisolas do {team} há no Kit Finder?"},
    "kfd_q_n_b": {"en": "How many {team} shirts can I find on Kit Finder?", "es": "¿Cuántas camisetas de {team} puedo encontrar en Kit Finder?",
                  "fr": "Combien de maillots {team} puis-je trouver sur Kit Finder ?", "de": "Wie viele {team}-Trikots finde ich auf Kit Finder?",
                  "it": "Quante maglie {team} posso trovare su Kit Finder?", "nl": "Hoeveel {team}-shirts kan ik op Kit Finder vinden?",
                  "pl": "Ile koszulek {team} mogę znaleźć w Kit Finder?", "pt": "Quantas camisolas do {team} posso encontrar no Kit Finder?"},
    "kfd_a_n": {"en": "As of {date}, Kit Finder lists {n} {team} shirts from {s} stores.",
                "es": "A {dnum}, Kit Finder tiene {n} camisetas de {team} de {s} tiendas.",
                "fr": "Au {dnum}, Kit Finder répertorie {n} maillots {team} provenant de {s} boutiques.",
                "de": "Stand {dnum} listet Kit Finder {n} {team}-Trikots aus {s} Shops.",
                "it": "Al {dnum}, Kit Finder elenca {n} maglie {team} di {s} negozi.",
                "nl": "Op {dnum} toont Kit Finder {n} {team}-shirts van {s} winkels.",
                "pl": "Na dzień {dnum} Kit Finder ma {n} koszulek {team} z {s} sklepów.",
                "pt": "A {dnum}, o Kit Finder lista {n} camisolas do {team} de {s} lojas."},
    "kfd_a_n1": {"en": "As of {date}, Kit Finder lists {n} {team} shirts, all from {store}.",
                 "es": "A {dnum}, Kit Finder tiene {n} camisetas de {team}, todas de {store}.",
                 "fr": "Au {dnum}, Kit Finder répertorie {n} maillots {team}, tous chez {store}.",
                 "de": "Stand {dnum} listet Kit Finder {n} {team}-Trikots, alle von {store}.",
                 "it": "Al {dnum}, Kit Finder elenca {n} maglie {team}, tutte di {store}.",
                 "nl": "Op {dnum} toont Kit Finder {n} {team}-shirts, allemaal van {store}.",
                 "pl": "Na dzień {dnum} Kit Finder ma {n} koszulek {team}, wszystkie ze sklepu {store}.",
                 "pt": "A {dnum}, o Kit Finder lista {n} camisolas do {team}, todas de {store}."},
    "kfd_q_p_a": {"en": "How much does a {team} shirt cost?", "es": "¿Cuánto cuesta una camiseta de {team}?",
                  "fr": "Combien coûte un maillot {team} ?", "de": "Was kostet ein {team}-Trikot?",
                  "it": "Quanto costa una maglia {team}?", "nl": "Wat kost een {team}-shirt?",
                  "pl": "Ile kosztuje koszulka {team}?", "pt": "Quanto custa uma camisola do {team}?"},
    "kfd_q_p_b": {"en": "What do {team} shirts sell for?", "es": "¿A qué precio se venden las camisetas de {team}?",
                  "fr": "À quel prix se vendent les maillots {team} ?", "de": "Zu welchem Preis werden {team}-Trikots angeboten?",
                  "it": "A che prezzo si vendono le maglie {team}?", "nl": "Voor welke prijs worden {team}-shirts verkocht?",
                  "pl": "Za ile sprzedawane są koszulki {team}?", "pt": "A que preço se vendem as camisolas do {team}?"},
    "kfd_a_p": {"en": "Listed prices go from {min} to {max}. The middle price is {median} and the average is {avg} (converted to euros on {date}).",
                "es": "Los precios van de {min} a {max}. El precio mediano es {median} y la media {avg} (convertidos a euros el {dnum}).",
                "fr": "Les prix vont de {min} à {max}. Le prix médian est de {median} et la moyenne de {avg} (convertis en euros le {dnum}).",
                "de": "Die Preise reichen von {min} bis {max}. Der mittlere Preis liegt bei {median}, der Durchschnitt bei {avg} (in Euro umgerechnet am {dnum}).",
                "it": "I prezzi vanno da {min} a {max}. Il prezzo mediano è {median} e la media {avg} (convertiti in euro il {dnum}).",
                "nl": "De prijzen lopen van {min} tot {max}. De middelste prijs is {median} en het gemiddelde {avg} (omgerekend naar euro op {dnum}).",
                "pl": "Ceny wynoszą od {min} do {max}. Cena środkowa to {median}, a średnia {avg} (przeliczone na euro {dnum}).",
                "pt": "Os preços vão de {min} a {max}. O preço mediano é {median} e a média {avg} (convertidos em euros a {dnum})."},
    "kfd_q_s_a": {"en": "Which stores sell {team} shirts?", "es": "¿Qué tiendas venden camisetas de {team}?",
                  "fr": "Quelles boutiques vendent des maillots {team} ?", "de": "Welche Shops verkaufen {team}-Trikots?",
                  "it": "Quali negozi vendono maglie {team}?", "nl": "Welke winkels verkopen {team}-shirts?",
                  "pl": "Które sklepy sprzedają koszulki {team}?", "pt": "Que lojas vendem camisolas do {team}?"},
    "kfd_q_s_b": {"en": "Where can I buy {team} shirts?", "es": "¿Dónde puedo comprar camisetas de {team}?",
                  "fr": "Où acheter des maillots {team} ?", "de": "Wo kann ich {team}-Trikots kaufen?",
                  "it": "Dove posso comprare maglie {team}?", "nl": "Waar kan ik {team}-shirts kopen?",
                  "pl": "Gdzie kupić koszulki {team}?", "pt": "Onde posso comprar camisolas do {team}?"},
    "kfd_a_s": {"en": "The stores with the most {team} shirts on Kit Finder: {list}.",
                "es": "Las tiendas con más camisetas de {team} en Kit Finder: {list}.",
                "fr": "Les boutiques avec le plus de maillots {team} sur Kit Finder : {list}.",
                "de": "Die Shops mit den meisten {team}-Trikots auf Kit Finder: {list}.",
                "it": "I negozi con più maglie {team} su Kit Finder: {list}.",
                "nl": "De winkels met de meeste {team}-shirts op Kit Finder: {list}.",
                "pl": "Sklepy z największą liczbą koszulek {team} w Kit Finder: {list}.",
                "pt": "As lojas com mais camisolas do {team} no Kit Finder: {list}."},
    "kfd_q_o_a": {"en": "What is the oldest {team} shirt listed?", "es": "¿Cuál es la camiseta de {team} más antigua?",
                  "fr": "Quel est le plus ancien maillot {team} répertorié ?", "de": "Welches ist das älteste gelistete {team}-Trikot?",
                  "it": "Qual è la maglia {team} più vecchia in elenco?", "nl": "Wat is het oudste {team}-shirt in de lijst?",
                  "pl": "Jaka jest najstarsza koszulka {team} w ofercie?", "pt": "Qual é a camisola do {team} mais antiga?"},
    "kfd_q_o_b": {"en": "How far back do the {team} shirts go?", "es": "¿Hasta qué año se remontan las camisetas de {team}?",
                  "fr": "Jusqu'à quand remontent les maillots {team} ?", "de": "Wie weit reichen die {team}-Trikots zurück?",
                  "it": "Fino a che anno risalgono le maglie {team}?", "nl": "Hoe ver gaan de {team}-shirts terug?",
                  "pl": "Jak stare są najstarsze koszulki {team}?", "pt": "Até que ano recuam as camisolas do {team}?"},
    "kfd_a_o": {"en": "The earliest season listed is {oldest}. The most recent is {newest}.",
                "es": "La temporada más antigua es {oldest}. La más reciente, {newest}.",
                "fr": "La saison la plus ancienne est {oldest}. La plus récente, {newest}.",
                "de": "Die älteste gelistete Saison ist {oldest}, die neueste {newest}.",
                "it": "La stagione più vecchia è il {oldest}. La più recente il {newest}.",
                "nl": "Het oudste seizoen is {oldest}. Het nieuwste {newest}.",
                "pl": "Najstarszy sezon to {oldest}. Najnowszy to {newest}.",
                "pt": "A época mais antiga é {oldest}. A mais recente, {newest}."},

    # ── Otros ──────────────────────────────────────────────────────────
    "kfd_note": {"en": "Data from Kit Finder's index on {date}. Prices are converted to euros at current exchange rates; each store sells in its own currency.",
                 "es": "Datos del índice de Kit Finder a {dnum}. Precios convertidos a euros al cambio actual; cada tienda vende en su propia moneda.",
                 "fr": "Données de l'index Kit Finder au {dnum}. Prix convertis en euros au taux actuel ; chaque boutique vend dans sa propre devise.",
                 "de": "Daten aus dem Kit-Finder-Index vom {dnum}. Preise zum aktuellen Kurs in Euro umgerechnet; jeder Shop verkauft in seiner eigenen Währung.",
                 "it": "Dati dall'indice di Kit Finder al {dnum}. Prezzi convertiti in euro al cambio attuale; ogni negozio vende nella propria valuta.",
                 "nl": "Gegevens uit de index van Kit Finder op {dnum}. Prijzen omgerekend naar euro tegen de huidige koers; elke winkel verkoopt in zijn eigen valuta.",
                 "pl": "Dane z indeksu Kit Finder na dzień {dnum}. Ceny przeliczone na euro po bieżącym kursie; każdy sklep sprzedaje we własnej walucie.",
                 "pt": "Dados do índice do Kit Finder a {dnum}. Preços convertidos em euros ao câmbio atual; cada loja vende na sua própria moeda."},
    "kfd_none": {"en": "There are no {team} shirts listed on Kit Finder right now. New stock is added every day.",
                 "es": "Ahora mismo no hay camisetas de {team} en Kit Finder. Cada día se añade stock nuevo.",
                 "fr": "Aucun maillot {team} n'est répertorié sur Kit Finder pour le moment. Du nouveau stock arrive chaque jour.",
                 "de": "Derzeit sind keine {team}-Trikots auf Kit Finder gelistet. Jeden Tag kommen neue Angebote dazu.",
                 "it": "Al momento non ci sono maglie {team} su Kit Finder. Ogni giorno arriva nuova disponibilità.",
                 "nl": "Er staan op dit moment geen {team}-shirts op Kit Finder. Er komt elke dag nieuwe voorraad bij.",
                 "pl": "Obecnie w Kit Finder nie ma koszulek {team}. Nowe oferty pojawiają się codziennie.",
                 "pt": "Neste momento não há camisolas do {team} no Kit Finder. Todos os dias entra stock novo."},
    "kfd_related": {"en": "Related", "es": "Relacionados", "fr": "À voir aussi", "de": "Ähnliche Seiten", "it": "Correlati",
                    "nl": "Gerelateerd", "pl": "Powiązane", "pt": "Relacionados"},
}

LANGS = ["en", "es", "fr", "de", "it", "nl", "pl", "pt"]
